variables:
  repository: 'jannemattila/webapp-update'

trigger:
- main
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: PowerShell@2
      script:
        echo $(Build.BuildNumber) > src/WebApp/wwwroot/release.txt
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext:
        tags: |
          $(Build.BuildNumber)
          latest
